### ISSUE TITLE
In Search map, count text shown in markers is incorrect.

### ISSUE THREAD

**Issue by gku11ava** [daveegrant/ml-esri-maps-ng#2]
When a single dataset is provided with multiple boxes as in the example data, the count text displayed for all 3 markers is the count from the last box.

**Comment by daveegrant** [comment]
Thanks for the feedback.  I just tried using the data from the example data and got different counts for each box. The code uses the 'count' property of the object in the array for 'boxes'.  The 'count' property of the object in 'locations' is ignored.

Would you be able to provide the facet data you used that has the reported problem?

**Comment by daveegrant** [comment]
I was able to recreate this issue today.  Working on it now.
